// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAqi9s6mH2XohvdNQ2__V4B7jR0rY-wSA',
    appId: '1:1077494402266:web:e29555cb47851f683c29e3',
    messagingSenderId: '1077494402266',
    projectId: 'ahmad-simple-task',
    authDomain: 'ahmad-simple-task.firebaseapp.com',
    storageBucket: 'ahmad-simple-task.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvOvVVlNajb3IodiDY2whNk-pdL0EPfdA',
    appId: '1:1077494402266:android:109ff0b7bea462883c29e3',
    messagingSenderId: '1077494402266',
    projectId: 'ahmad-simple-task',
    storageBucket: 'ahmad-simple-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9twDRE6SBSXDBlMhuVcc2pBBZcTI7yCo',
    appId: '1:1077494402266:ios:fb761f13d509137b3c29e3',
    messagingSenderId: '1077494402266',
    projectId: 'ahmad-simple-task',
    storageBucket: 'ahmad-simple-task.appspot.com',
    iosBundleId: 'com.example.eolFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9twDRE6SBSXDBlMhuVcc2pBBZcTI7yCo',
    appId: '1:1077494402266:ios:fb761f13d509137b3c29e3',
    messagingSenderId: '1077494402266',
    projectId: 'ahmad-simple-task',
    storageBucket: 'ahmad-simple-task.appspot.com',
    iosBundleId: 'com.example.eolFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAqi9s6mH2XohvdNQ2__V4B7jR0rY-wSA',
    appId: '1:1077494402266:web:49c63e5dec8b95c03c29e3',
    messagingSenderId: '1077494402266',
    projectId: 'ahmad-simple-task',
    authDomain: 'ahmad-simple-task.firebaseapp.com',
    storageBucket: 'ahmad-simple-task.appspot.com',
  );
}
